name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  provider: ^6.1.5
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.2.0
  http: ^1.4.0
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  firebase_storage: ^12.4.5
  cached_network_image: ^3.4.1
  video_player: ^2.9.5
  video_thumbnail: ^0.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 23
