// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm34cqN2VfzJtoFgQDpH7XpOq24qWccgo',
    appId: '1:97420003869:web:ad94947abba5fcab6514f4',
    messagingSenderId: '97420003869',
    projectId: 'chatapp-3e129',
    authDomain: 'chatapp-3e129.firebaseapp.com',
    storageBucket: 'chatapp-3e129.firebasestorage.app',
    measurementId: 'G-HHR6YPRPQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ4mgI00Dcglre-MucvQgU58v7xW6VfmQ',
    appId: '1:97420003869:android:369647fc12e838606514f4',
    messagingSenderId: '97420003869',
    projectId: 'chatapp-3e129',
    storageBucket: 'chatapp-3e129.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ1hhra46Rei9bldQtEJ5t5DjTUXu_lI8',
    appId: '1:97420003869:ios:a32c364f5cb2a06b6514f4',
    messagingSenderId: '97420003869',
    projectId: 'chatapp-3e129',
    storageBucket: 'chatapp-3e129.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ1hhra46Rei9bldQtEJ5t5DjTUXu_lI8',
    appId: '1:97420003869:ios:a32c364f5cb2a06b6514f4',
    messagingSenderId: '97420003869',
    projectId: 'chatapp-3e129',
    storageBucket: 'chatapp-3e129.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm34cqN2VfzJtoFgQDpH7XpOq24qWccgo',
    appId: '1:97420003869:web:0b44cf64e975c5c06514f4',
    messagingSenderId: '97420003869',
    projectId: 'chatapp-3e129',
    authDomain: 'chatapp-3e129.firebaseapp.com',
    storageBucket: 'chatapp-3e129.firebasestorage.app',
    measurementId: 'G-PP20MEJ5GD',
  );
}
